<template>
	<div class="staDiv tipsDiv">
	  <div class="stabox">
	  	<h3 class="tipTitle">Step tips</h3>
	  	<ul v-for="(item,index) in stepTips" :key="index" v-if="step==item.step && !singleStep">
	  		<li v-for="(item,index) in item.infolist" :key="index">{{item}}</li>
	  	</ul>
	  	
	  	<ul v-for="(item,index) in stepTips" :key="index" v-if="singleStep">
	  		<li v-for="(item,index) in item.infolist" :key="index">{{item}}</li>
	  	</ul>
	  	
	  	
	  	<!--<a class="btn_next"></a>-->
	  </div>
	  <div class="transbox" v-if="confirShow"></div>
	  <div class="confirmBox " :class="{'show':confirShow,'a-ma-confirmBox':pageName==54 && step==1}">
	  	
	  	<div class="c_box">
	  		<p class="title">{{tipTiltle}}</p>
	  		<p>{{confirmInfo}}</p>
	  		
	  	</div>
	  	<a class="sureBtn" @click="sureTip">I got it!</a>
	  	<div class="icon"></div>
	  </div>
	  
	  <template v-if="pageName==3">
	  <div class="transbox" v-if="isShowAttack">  	 
	  </div>
	  <div class="confirmBox fileConfirmBox" :class="{'show':isShowAttack}">
	 	  <div class="c_box">
  	 	  <p class="title">Please note that!</p>
  	 	  <p>Currently user a is preparing to send "file a" to user B. do you want to assign user C to attack this file?</p>
  	 	  <div class="btnbox">
  	 	  	 <a class="chooseBtn" @click="attackMode(1)">Attack</a>
  	 	  	 <a class="chooseBtn" @click="attackMode(2)">No attack</a>
  	 	  </div> 
	 	  </div>
	 	  <div class="icon"></div>
	 </div>
	  </template>
	  <!--椭圆线是否展示-->
	  <template v-if="pageName==5">
	  	 <div class="transbox" v-if="lineDrawShow">    
	     </div>
	     <div class="confirmBox fileConfirmBox eccConfirmBox n-eccConfirmBox_1" :class="{'show':lineDrawShow}">
			 	  <div class="c_box">
		  	 	  <p class="title">Elliptic curve：y²=x²+ax+b</p>
		  	 	  <p class="c_mess">(different ellipses are generated by inputting different a and b values below）</p>
		  	 	  <div class="ecc-in">
		  	 	  	 <div class="e-in"><label>a:</label><input placeholder="Please enter a value of 1-3" v-model="a" maxlength="1" @input='showLine'/></div>
		  	 	  	 <div class="e-in e-in-last"><label>b:</label><input placeholder="Please enter a value of 1-3" v-model="b" maxlength="1" @input='showLine'/></div>  	 
		  	 	  </div>
		  	 	  <div class="ec-img"><img :src="abimg"/></div>
		  	 	  <div class="btnbox">
		  	 	  	 <a class="chooseBtn" @click="sureLine">Sure</a>	  	 	  	 
		  	 	  </div> 
			 	  </div>
			 	  <div class="icon"></div>
			 </div>
	  </template>
	  
	  <!--椭圆线划线成功-->
	  <template v-if="pageName==5">
	  	 <div class="transbox" v-if="lineFinsh">    
	     </div>
	     <div class="confirmBox fileConfirmBox eccConfirmBox n-eccConfirmBox_2" :class="{'show':lineFinsh}">
			 	  <div class="c_box">
		  	 	  <p class="title result_title">Suppose we have a point (3, 4) now. We add this point for 10 times to get a new point (9, 6), as shown in the figure below：</p>		  	 	  
		  	 	  <div class="ec-img result-img"><img src="../assets/ecc/result.jpg"/></div>
		  	 	  <p class="c_mess result_mess">Through the point addition calculation, we can know that the number of addition is the private key, and the new point is the public key：</p>
		  	 	  <p class="c_mess result_mess">Private key：d2qwe3q1we25q1we3q2w12fas5f14dgf51wer2w1erew</p>
		  	 	  <p class="c_mess result_mess">Public key：21w32e1wq5r12f1s5ewr1w3er12ew3r1we5we1twe35q</p>
		  	 	  <div class="btnbox">
		  	 	  	 <a class="chooseBtn" @click="surePoint">Sure</a>	  	 	  	 
		  	 	  </div> 
			 	  </div>
			 	  <div class="icon"></div>
			 </div>
	  </template>
	  
	  <!--椭圆线-->
    <template v-if="pageName==5">
		  <div class="transbox" v-if="isParse">  	 
		  </div>
		  <div class="confirmBox fileConfirmBox parseconfirmbox" :class="{'show':isParse}">
		 	  <div class="c_box">
	  	 	  <p class="title">Please note that!</p>
	  	 	  <p class="pintro">
	  	 	  	 {{step==2?'Encrypted data is being transmitted. C user tries to use public key to crack data.':'Encrypted data has been transferred successfully. User B uses his private key to parse the data.'}}
	  	 	  </p>
	  	 	  <div class="progress" >
						<div class="curPro">
							<div class="proIcon" :style="{'width':wprogress+'%'}" v-if="wprogress!=100"></div>
							<p class="failtext" v-if="wprogress==100">{{step=='2'?'Analysis failed!':'Analysis success!'}}</p>
						</div>
					</div>
					<p class="pintro functintro" v-if="wprogress==100">
						{{step==2?'The public key is used for encryption and the private key is used for decryption. It is not feasible to calculate the private key from the public key.':'Congratulations on your successful parsing. The data content is as follows：XXXXXXXXXXXXXXXXXXXXXXX'}}
					</p>
					<div class="btnbox">
	  	 	  	 <a class="chooseBtn" @click="sureParse" v-if="wprogress==100">Sure</a>	  	 	  	 
	  	 	  </div>
		 	  </div>
		 	  <div class="icon"></div>
		 </div>
	  </template >
	  
	  <!--加密算法操作提示框异常篇52软分叉，56智能合约,57硬分叉-->
	  <template v-if="pageName==6 || pageName==4 || pageName==56 || pageName==52 || pageName==57">
	  	 <div class="transbox" v-if="isPrompt" ></div>
	  	 <div class="confirmBox promptBox" :class="{'show':isPrompt}">
	  	 	  <p class="pintro">
	  	 	  	 {{promptText}}
	  	 	  </p>
	  	 	  <div class="com-btnBox">
	  	 	  	<span class="com-btn" @click="surePrompt">确定</span>
	  	 	  </div>
	  	 	  <div class="icon"></div>
	  	 </div>
	  	 
	  </template>
	  
	  
	  <!--51%攻击转账-->
    <template v-if="pageName==51  && step==1">
      <div class="transbox" v-if="lineDraw51Show && step<=2" @click="hideLineDrawShow"></div>
      <div class="confirmBox fileConfirmBox confirmBox51"  :class="{'show':lineDraw51Show}" 
      	style="width:350px;height:380px;margin-left: -170px;margin-top: -200px;font-size: 18px">
        <div class="c_box">
          <div class="main_form">
            <div class="cr_din">
              <span class="lab">Account balance:</span>
              <div  class="lab_in">
                <span>￥{{balance}}</span>
              </div>
            </div>
           <div class="cr_din">
              <span class="lab">Available balance:</span>
              <div class="lab_in">
                <span>￥{{useBalance}}</span>
              </div>
            </div>
            <div class="cr_din" >
              <span class="lab">Transfer initiation:</span>
              <div class="lab_in">
                <div style="margin: auto;padding: 0;width:150px">
                  <i-select v-model="tansferInfo.initiate" @on-change="selectUser">
                    <i-option v-for="(item,index) in userList" :value="item.userId" :key="index">{{item.name}}</i-option>
                  </i-select>
                </div>
              </div>
            </div>
            <div class="cr_din">
              <span class="lab">Transfer object:</span>
              <div class="lab_in">
                <div style="margin: auto;padding: 0;width:150px">
                  <i-select v-model="tansferInfo.object">
                     <i-option v-for="(item,index) in toList" :value="item.userId" :key="index">{{item.name}}</i-option>
                  </i-select>
                </div>
              </div>
            </div>
            <div class="cr_din" >
              <span class="lab">Transfer amount:</span>
              <div class="lab_in">
                <div><i-input  placeholder="" v-model="tansferInfo.amount" style="width:150px"></i-input></div>
              </div>
            </div>
          </div>
          <div class="btnbox">
            <a class="chooseBtn" @click="sureTransfer(1)">Confirm transfer</a>
          </div>
        </div>
        <div class="icon"></div>
      </div>
    </template>
    <!--提升算力-->
    <template v-if="pageName==51  && step==2">
      <div class="transbox" v-if="lineDraw51Show">
      </div>
      <div class="confirmBox fileConfirmBox confirmBox51" :class="{'show':lineDraw51Show}" style="width:340px;margin-left: -170px;margin-top: -200px;font-size: 18px">
        <div class="c_box">
          <div class="main_form">
            <div class="cr_din cr_din_obj" >
              <span class="lab" >Promotion object:</span>
              <div class="lab_in">
                <i-select style="width:150px" v-model="upComputeUser">
                  <i-option v-for="(item,index) in userList" :value="item.userId" :key="index">{{item.name}}</i-option>
                </i-select>
              </div>
            </div>
            <div class="cr_din cr_din_value">
              <span style="margin: auto;color: white">{{computevalue}}%</span>
              <div class="block" style="width:80%;margin: auto;">
                <el-slider v-model="computevalue"></el-slider>
              </div>
              <span style="margin: auto;color: white">Please increase the calculation power to as low as 51%</span>
            </div>
          </div>
          <div class="btnbox">
            <a class="chooseBtn" @click="sureUpCompute">Sure</a>
          </div>
        </div>
        <div class="icon"></div>
      </div>
    </template>
    <!--打包-->
    <template v-if="pageName==51 && step == 3 &&　!isShowDelete">
      <div class="transbox" v-if="lineDraw51Show">
      </div>
      <div class="confirmBox fileConfirmBox parseconfirmbox a-51parseconfirmbox " :class="{'show':lineDraw51Show}">
        <div class="c_box">
          <p class="pintro">
            Packaging remaining transactions
          </p>
          <div class="progress" >
            <div class="curPro">
              <div class="proIcon" :style="{'width':wprogress51+'%'}"></div>
            </div>
          </div>
          <!--<div class="btnbox">
            <a class="chooseBtn" @click="sureBale" v-if="wprogress51==100">确定</a>
          </div>-->
        </div>
        <div class="icon"></div>
      </div>
    </template >
    <!--删除提示-->
    <template v-if="pageName==51 && isShowDelete">
      <div class="transbox" v-if="lineDraw51Show ">
      </div>
      <div class="confirmBox fileConfirmBox eccConfirmBox block-51Confirmbox" :class="{'show':lineDraw51Show}">
        <div class="c_box">
          <p class="title">Please note that!</p>
          <p>Delete the transaction</p>
          <div class="btnbox">
            <a class="chooseBtn" @click="del">Sure</a>
            <a class="chooseBtn" @click="canc">Cancle</a>
          </div>
        </div>
        <div class="icon"></div>
      </div>
    </template>
    
    <!--交易延展性转账-->
    <template v-if="pageName==54  && step<=2 && editNumber==0 &&　!D1">
      <div class="transbox" v-if="lineDrawMalleabilityShow && step==1" @click="hideLineDrawShow">
      </div>
      <div class="confirmBox fileConfirmBox confirmBox51 " :class="{'show':lineDrawMalleabilityShow}" style="width:340px;margin-left: -170px;margin-top: -200px;font-size: 18px">
        <div class="c_box">
          <div class="main_form">
            <div class="cr_din">
              <span class="lab">Account balance:</span>
              <div  class="lab_in">
                <span>￥{{balance}}</span>
              </div>
            </div>
            <div class="cr_din" >
              <span class="lab">Transfer initiation:</span>
              <div class="lab_in">
                <div style="margin: auto;padding: 0;width:150px">
                  <i-select v-model="tansferInfo.initiate" @on-change="selectUser">
                    <i-option v-for="(item,index) in userList" :value="item.userId" :key="index">{{item.name}}</i-option>
                  </i-select>
                </div>
              </div>
            </div>
            <div class="cr_din">
              <span class="lab">Transfer object:</span>
              <div class="lab_in">
                <div style="margin: auto;padding: 0;width:150px">
                  <i-select v-model="tansferInfo.object">
                     <i-option v-for="(item,index) in toList" :value="item.userId" :key="index">{{item.name}}</i-option>
                  </i-select>
                </div>
              </div>
            </div>
            <div class="cr_din" >
              <span class="lab">Transfer amount:</span>
              <div class="lab_in">
                <div><i-input  placeholder="" v-model="tansferInfo.amount" style="width:150px"></i-input></div>
              </div>
            </div>
          </div>
          <div class="btnbox">
            <a class="chooseBtn" @click="sureTransfer(2)">Confirm transfer</a>
          </div>
        </div>
        <div class="icon"></div>
      </div>
    </template>
    <!--交易延展性修改-->
    <template v-if="pageName==54  && D1 &&　step<4">
      <div class="transbox" v-if="lineDrawMalleabilityShow && step==3" @click="hideLineDrawShow">
      </div>
      <div class="confirmBox fileConfirmBox eccConfirmBox am-affair-ConfirmBox" 
      	:class="{'show':lineDrawMalleabilityShow}" 
      	style="width:400px;margin-left: -170px;margin-top: -200px;font-size: 18px; height: 350px;">
        <div class="c_box">
          <div style="margin: auto;width:80%">
            <div class="cr_din" style="margin-top: 20px;color: white"> Transaction not packaged in chain intercepted </div>
            <div class="cr_din" style="display: flex;margin-top: 20px">
              <span class="lab" style="line-height: 32px;color:#fff">Select transaction:</span>
              <div style="margin: auto;padding: 0">
                <div style="margin: auto;padding: 0;width:200px">
                  <i-select v-model="selectIndexData" @on-change="upToEditAmount">
                    <i-option v-for="(item,index) in selectIndexDataM" :value="item.id" :key="index" v-if="!item.isEdit">事务{{index+1}}</i-option>
                  </i-select>
                </div>
              </div>
            </div>
            <div class="cr_din" style="display: flex;margin-top: 20px">
              <span class="lab" style="line-height: 32px;color:#fff">Revised amount:</span>
              <div style="margin: auto;padding: 0;width:200px">
                <input class="a-mallattack-input" :placeholder="'Only the amount can be modified to' + toEditAmount" style="width:100%;border-radius: 5px" type="" v-model="editAmount"/>
              </div>
            </div>
          </div>
          <div class="btnbox">
            <a class="chooseBtn" @click="sureEditAmount">Confirm modification</a>
          </div>
        </div>
        <div class="icon"></div>
      </div>
    </template>
    <!--打包-->
    <template v-if="pageName==54 && step == 4">
      <div class="transbox" v-if="lineDrawMalleabilityShow">
      </div>
      <div class="confirmBox fileConfirmBox parseconfirmbox" :class="{'show':lineDrawMalleabilityShow}"
      	 style="height: 280px;"
      	>
        <div class="c_box">
          <p class="pintro">The original transfer data and the modified data are competing to pack into blocks!</p>
          <div class="progress" >
            <div class="curPro">
              <div class="proIcon" :style="{'width':wprogressmalleability+'%'}"></div>
            </div>
          </div>
          <!--<div class="btnbox">
            <a class="chooseBtn" @click="sureBale" v-if="wprogress51==100">确定</a>
          </div>-->
        </div>
        <div class="icon"></div>
      </div>
    </template >
    
    <!--重放攻击广播-->
     <template v-if="pageName==53 && (broadcastNumber==1 &&　step==2)　||　(broadcastNumber==2 &&　step==4)">
      <div class="transbox" v-if="lineDraw53Show">
      </div>
      <div class="confirmBox fileConfirmBox parseconfirmbox replay-confirmBox " :class="{'show':lineDraw53Show}">
        <div class="c_box">
          <p class="pintro">{{step==2?'The transfer from user a to user B is being broadcast':'At present, the hacker intercepts the transaction to broadcast in the B chain'}}</p>
          <div class="progress" >
            <div class="curPro">
              <div class="proIcon" :style="{'width':wprogress+'%'}"></div>
            </div>
          </div>
        </div>
        <div class="icon"></div>
      </div>
    </template >
    <!--重放攻击截获-->
    <template v-if="pageName==53 &&　step==3">
      <div class="transbox" v-if="lineDraw53Show">
      </div>
      <div class="confirmBox fileConfirmBox parseconfirmbox replay-confirmBox" :class="{'show':lineDraw53Show}">
        <div class="c_box">
          <p class="pintro">Note that hackers are intercepting transactions that are not packaged into the chain</p>
          <div class="progress" >
            <div class="curPro">
              <div class="proIcon" :style="{'width':wprogress+'%'}"></div>
            </div>
          </div>
        </div>
        <div class="icon"></div>
      </div>
    </template >
    <!--重放攻击打包-->
    <template v-if="pageName==53 && step==5">
      <div class="transbox" v-if="lineDraw53Show">
      </div>
      <div class="confirmBox fileConfirmBox parseconfirmbox replay-confirmBox" :class="{'show':lineDraw53Show}">
        <div class="c_box">
          <p class="pintro">Packaging transaction</p>
          <div class="progress" >
            <div class="curPro">
              <div class="proIcon" :style="{'width':wprogress+'%'}"></div>
            </div>
          </div>
        </div>
        <div class="icon"></div>
      </div>
    </template >
	  <!--重放攻击-->
		<template v-if="pageName==53">
		  <div class="transbox" v-if="D2"  @click="hideTrans">
		  </div>
		  <div class="confirmBox fileConfirmBox eccConfirmBox a-replay-attack" style="margin-top: -240px" :class="{'show':D2}">
		    <div class="c_box">
		      <div class="ecc-in">
		        <div class="e-in"><span>Transfer initiation: user 1</span></div>
		      </div>
		      <div class="ecc-in">
		        <div class="e-in"><span>Transfer object: User 2</span></div>
		      </div>
		      <div class="ecc-in">
		        <div class="e-in"><span>Transfer amount:</span><input placeholder="Please enter the transfer amount"  maxlength="3" v-model="aa_vaule"  @change="validateNum($event)"/></div>
		      </div>
		      <div class="ecc-in">
		        <div class="e-in"><span>Balance of transfer initiation：∞</span></div>
		      </div>
		      <div class="btnbox">
		        <a class="chooseBtn" @click="D2click">Confirm transfer</a>
		      </div>
		    </div>
		    <div class="icon"></div>
		  </div>
		</template>

		<!--合约漏洞提现金额-->
		<template v-if="pageName==56" >
			  <div class="transbox" v-if="D1" >
			  </div>
			  <div class="confirmBox fileConfirmBox eccConfirmBox" style="margin-top: -240px;height: 300px" :class="{'show':D1}">
			    <div class="c_box">
			      <div class="ecc-in" style="margin-top:40px;">
			        <div class="e-in"><label style="left: -60px;">Withdrawal amount:</label><input placeholder="Please enter the transfer amount"  maxlength="10"  value="1" readonly="true"/></div>
			      </div>
			      <div class="btnbox">
			        <a class="chooseBtn" @click="D1click">确定提现</a>
			      </div>
			    </div>
			    <div class="icon"></div>
			  </div>
		</template>

	</div>
</template>

<script>
	export default{
		data(){
			return{				
				tipTiltle:'',//弹出确认框的标题
			  confirmInfo:'',
			  isAttack:0,
			  
			  a:'',//椭圆线a的值
			  b:'',//椭圆线b的值
			  abimg:require('../assets/ecc/11.jpg'),//根据a、b生成的椭圆线
			  lineFinsh:false,//椭圆线是否生成
			   /*51%攻击*/
        computevalue: 0, //算力值
        tansferInfo: {
          initiate: '',
          object: '',
          amount: ''
        },
        upComputeUser: 'no one', //提升算力对象
        editAmount: '', //异常篇-交易延展性攻击
        
        toList:[], //51%攻击可转对象list
        balance: 0,//账户余额
        useBalance:0, //可用余额
        selectIndexData:'',//交易延展性当前修改的事务
        aa_vaule:'',//重放攻击转账金额
			}
		},
		//pageName为1表示当前页面是节点操作   2发币  3hash算法 4keyStore模拟  5椭圆线密码  2-4区块链+版权  
		//confirShow:''是否展示提示框
		//winNum：表示胜出的节点
		props:{confirShow:Boolean,pageName:null,step:Number,stepTips:null,winNum:null,
			 isShowAttack:{
			 	type:Boolean,
			 	default:false
			 },
			 //椭圆线画图是否展示
			 lineDrawShow:{
			 	 type:Boolean,
			 	 default:false
			 },
			 //解析进度
			 wprogress:{
			 	type:null,
			 	default:0
			 },
			 //解析那个进度是否显示
			 isParse:{
			 	type:Boolean,
			 	default:false
			 },
			 //是否是操作提示款
			 isPrompt:{
			 	 	type:Boolean,
			   	default:false
			 },
			 //提示框输入的内容是否正确
			 isRight:{
			 		type:Boolean,
			   	default:false
			 },
			 //提示内容
			 promptText:{
			 	 	type:null,
			   	default:''
			 },
			 
			 //是否是一个步骤提示
			 singleStep:{
			   	type:Boolean,
			   	default:false
			 },
			toEditAmount: '',
			 // 51%攻击是否显示
       lineDraw51Show: {
         type:Boolean,
         default:false
       },
       //51攻击用户列表
       userList:{
       	type:Array,
		    default:function(){
            return []
        }
       },
      // 解析进度
       wprogress51:{
         type:null,
         default:0
       },
       isShowDelete:{
       	type:null,
        default:false
       },
      // 延展性攻击
      lineDrawMalleabilityShow: {
        type:Boolean,
        default:false
      },
      editNumber:{
      	type:null,
      	default:0
      },
      selectIndexDataM: {
		    type:Array,
		    default:function(){
            return []
        }
      },
      //合约提现
      D1:{
        type:Boolean,
        default:false
      },
      //重放攻击转账
      D2:{
        type:Boolean,
        default:false
      },
      lineDraw53Show: {
        type:Boolean,
        default:false
      },
      inputMoney: {
        type:null,
        default:false
      },
      wprogressmalleability:{
        type:null,
        default:0
      },
      //重放攻击广播次数
      broadcastNumber:{
        type:null,
        default:0
      },
      //是否截获
      
      isIntercept:{
        type:null,
        default:false
      }
      
			
		},
		
		watch:{
			 
		 'a': function(val){
				this.a = val.replace(/[^1-3]/g, '')
				
			},
      
      'b': function(val){
				this.b = val.replace(/[^1-3]/g, '')
			},
			
			//51%攻击	
			'lineDraw51Show':function(){
        this.tansferInfo.initiate='';
        this.tansferInfo.object='';
        this.tansferInfo.amount='';
        this.balance=0
        this.useBalance=0
		  },
		  //交易延展性
		  'lineDrawMalleabilityShow':function(){
        this.tansferInfo.initiate='';
        this.tansferInfo.object='';
        this.tansferInfo.amount='';
        this.balance=0
		  },
		  //重放攻击
		  'D2':function(){
		  	this.aa_vaule='';
		  },
			  

			'confirShow':function(){
				let that = this;	
				if(that.pageName=='1'){ 	 
				  that.confirmInfo = that.step==1?'All nodes have been started. Please follow the prompt bar on the right to proceed to the next step.':that.step==2?'Node difficulty calculation has been completed. Congratulations on the success of node '+that.winNum+'follow the steps on the right'+
'Prompt bar for next operation.':'The winning node has completed the block packing and broadcast successfully. In order to reward the hard work of the node, the system will give a certain reward! At this point, the simulation run of the node has ended. The user can click Reset in the upper right corner to operate again, or return to the main interface to select another chapter.'	  
				   return;
				}
			  if(that.pageName=='2'){
			    switch(that.step){
				   case 1:
				   	that.confirmInfo = 'There are four users in the current network, please follow the prompt bar on the right to proceed to the next step'
				   	break;
				   case 2:
				   	that.confirmInfo = 'The initial setting of currency has been completed, please follow the prompt bar on the right to proceed to the next step.'
				   	break;
				   case 3:
				   	that.confirmInfo = 'A smart transfer contract has been deployed. You can transfer money with other users!'
				   	break;
			   }				
				   return;
				}
			 if(that.pageName=='2-multiple'){
			 	switch(that.step){
				   case 1:
				   	that.confirmInfo = 'There are four users in the current network, please follow the prompt bar on the right to proceed to the next step.'
				   	break;
				   case 2:
				   	that.confirmInfo = 'The initial setting of currency has been completed, please follow the prompt bar on the right to proceed to the next step.'
				   	break;
				   case 3:
				   	that.confirmInfo = '一个转账智能合约已部署完毕，你可以和其他用户之间进行相互转账啦！'
				   	break;
			   }				
				   return;
			 }
			 if(that.pageName == '3'){
			 	   if(that.confirShow ==true){
				   switch(that.step){
					   case 0:
					    that.tipTiltle = 'Basic concepts and characteristics of hash algorithm'
					   	that.confirmInfo = 'Hash algorithm is a one-way cryptographic mechanism in blockchain to ensure that the transaction information is not tampered. After receiving an inscription, hash algorithm transforms it into a short hash data with fixed number of bits in an irreversible way. It has two characteristics: first, the encryption process is irreversible, which means that we can not deduce the original inscription from the output hash data; The other is that the input inscription corresponds to the output hash data one by one. Any change of input information will lead to the change of the final output hash data'
					   	break;
					   case 1:
					    that.tipTiltle = 'Please note that!';
					   	that.confirmInfo = 'The hash value has been generated for "file a" through hash calculation. Please follow the prompt bar on the right to proceed to the next step'
					   	break;
					   case 2:
					    that.tipTiltle = 'Please note that!'; 
					   	that.confirmInfo = this.isAttack==1?'"File a" was attacked by user C in the process of transmission!':'"File a" is transferred successfully. No attack happened in the middle!'
					   	break;
					   	case 3:
					    that.tipTiltle = '';
					    let tmp ='Through the simulation of hash algorithm in this scenario, we can understand that in the blockchain, the hash value can uniquely and accurately identify a block. Any node in the blockchain can obtain the hash value of the block through simple hash calculation, and the calculated hash value does not change, which means that the information in the block has not been tampered with, and vice versa. Hash algorithm simulation has ended, click the reset button on the top right to experience it again.'
					    that.confirmInfo = this.isAttack==1?'The "file a" sent by a has been tampered with, and the hash value has changed!'+tmp:
					    'The "file a" transmitted by a has not been tampered with, and the hash value has not changed!'+tmp
					   	//that.confirmInfo = '哈希算法模拟已结束，大概概括模拟内容，并告知可通过右上方重置 按钮体验“攻击”时的模拟情况。'
					   	break;
				   }
					return;
					}
				}
			 if(that.pageName == '4'){
					that.confirmInfo = 'Through the keysore simulation of this scenario, we can see that this is a way to encrypt and protect the private key through symmetric encryption, and the characters generated after encryption are keysore. Keysotre simulation is over. Click the reset button on the top right to experience it again.'
					return; 
				}
			 
			 if(that.pageName == '5'){
			 	if(that.confirShow == true){
				 	 switch(that.step){
					   case 1:
					    that.tipTiltle = 'Basic concepts and characteristics of elliptic line cryptography'
					   	that.confirmInfo = 'Elliptic curve cryptography is a public key encryption algorithm based on elliptic curve mathematics. It belongs to asymmetric encryption algorithm and needs two keys public key and private key. In the blockchain, it is convenient to generate public and private keys by using elliptic curve, with high processing speed and high security.'
					   	break;
					   case 2:
					      that.tipTiltle = 'Please note that!'
					      that.confirmInfo = 'User B has successfully generated the public key and private key through the elliptic line cryptography algorithm, and published the public key.'
					    break;
					   	case 4:
					    that.tipTiltle = '';
					   	that.confirmInfo = 'Through the simulation of ellipse algorithm in this scenario, we can intuitively understand the process of using ellipse to generate public key and private key, and how to use public key and private key to encrypt and decrypt data. Ellipse algorithm simulation has ended, click the reset button on the top right to experience it again.'
					   	break;
				   }
				 	 return; 
			  }
			 }
	     if(that.pageName == '6'){
			 	 switch(that.step){
				   case 0:
				    that.tipTiltle = 'Basic concepts and characteristics of symmetric encryption'
				   	that.confirmInfo = 'The basic concept and characteristics of symmetric encryption: using single key encryption method, the same key can be used to encrypt and decrypt at the same time, this encryption method is called symmetric encryption. It is characterized by open algorithm, small amount of calculation and fast encryption speed, but it needs to share the key in advance. Once the key is leaked, the encrypted information will be cracked.'
				   	break;
				   	case 3:
               that.tipTiltle = '';
				   	that.confirmInfo = 'Through the simulation of symmetric key algorithm in this scenario, we use a simple single key to encrypt and decrypt the data. Symmetric key algorithm simulation has ended, click the reset button on the top right to experience it again.'
				   	break;
			   }
			 	 return; 
			 }
	     if(that.pageName == '2-1'){
					that.confirmInfo = 'In this scenario, we change different roles (hospital A / B / C and patient) to experience the practical application of blockchain in medical record information sharing and patient privacy protection. So far, the case information sharing scene has been simulated. Click the reset button in the upper right corner to experience it again.'
					return					
				}
	     if(that.pageName == '2-2'){
					that.confirmInfo = 'In this scenario, as different roles in the donation process (donor, Red Cross, beneficiary), we experienced the practical application of blockchain in dealing with the public trust crisis. So far, the donation data confirmation scene has been simulated. Click the reset button in the upper right corner to experience it again.'
					return					
				}
			 if(that.pageName == '2-3'){
					that.confirmInfo = 'In this scenario, we have experienced the practical application of blockchain in data storage as different roles (registrant, publishing house and verification office) in the process of copyright registration. So far, the scene of copyright preservation has been simulated. Click the reset button in the upper right corner to experience it again.'
					return					
				}
			 if(that.pageName == '2-4'){
					that.confirmInfo = 'In this scenario, as different roles in the logistics process (sender, collection point, logistics, recipient), we experienced the practical application of blockchain in accurate traceability. So far, the logistics process traceability scenario has been simulated. Click the reset button in the upper right corner to experience it again.'
					return					
				}
			 if(that.pageName == '2-5'){
					that.confirmInfo = 'In this scenario, as different roles in Supply Chain Finance (suppliers, core enterprises and banks), we have experienced the practical application of blockchain to solve the problem of small and medium-sized enterprises difficulty in lending to banks. So far, the scene of supply chain financial audit has been simulated. Click the reset button in the upper right corner to experience it again.'
					return					
				}
			 if(that.pageName == '2-6'){
					that.confirmInfo = 'In this scenario, we have experienced the practical application of blockchain in simplifying the claim process as different roles (policyholder, airline and insurance company) in the processing of aviation delay insurance. So far, the fast policy processing scene has been simulated. Click the reset button in the upper right corner to experience it again.'
					return					
				}
			 
			 if(that.pageName == '51') {
			 	 //console.log(that.step)
          switch(that.step){
            case 1:
              //表示转账发起的弹出框
              //console.log(that.D1+'1233')
              if(that.D1){
              	that.tipTiltle = 'Please note that'
                that.confirmInfo = 'The transfer transaction has been initiated, the block is waiting to be packaged, and has not yet entered the main chain.'
              }else{
              	that.tipTiltle = 'Basic concept and harm of 51% attack'
                that.confirmInfo = 'The so-called 51% computing power attack means that when a transaction has occurred but is still in the memory pool waiting to be packaged, that is, it has not been recorded in the main chain, the attacker takes advantage of his own computing power to occupy the packaging right and tamper with the records on the blockchain, so as to achieve the purpose of canceling the paid transaction. Once the computing power attack occurs, people confidence in the blockchain network will drop to the freezing point, and the currency value of the blockchain currency will be severely damaged.'
              }
              
              break;
            case 2:
              that.tipTiltle = 'Please note that'
              that.confirmInfo = 'current' + that.upComputeUser + 'The user computing power has reached 51%, which is more than half of that of the whole network' + that.upComputeUser + 'It has the function of attacking blockchain network security'
              break;
            case 4:
              
              break;
            case 12:
              that.tipTitle = ''
              that.confirmInfo = '51% attack is possible, but from the perspective of economic benefits, it costs a lot to occupy the dominant computing power. Once an attack is launched, it will cause a sharp drop in the value of the currency, and in the end, it may not be worth the loss. So in reality, the possibility is not high. So far, the attack process of 51% attack has been simulated. Click the reset button in the upper right corner to experience it again.'
              break;
          }
          return;
        }
        if(that.pageName == '54') {
          switch(that.step){
            case 1:
              that.tipTiltle = 'The basic concept and harmfulness of transaction malleability'
              that.confirmInfo = 'Transaction malleability stems from an error in bitcoin source code. This error can change the transaction ID without changing the transaction output or transaction content. This error means that the transaction signature can be changed before the transaction is written to the block. In other words, an unconfirmed bitcoin transaction may be hacked into two legitimate transactions. Although the miner will only confirm one transaction in the end, and the output of the transaction remains unchanged, your bitcoin will be transferred to the expected payee. However, the change of transaction ID will cause the subsequent hash values to change completely. Hackers can use transaction malleability to attack exchanges. Part of the reason that Mt. GOx, once the biggest bitcoin exchange, announced its collapse was the malleability attack'
              break;
            case 2:
              that.tipTiltle = 'Please note that'
              that.confirmInfo = 'The transfer has been initiated successfully, but the block has not been packaged into the chain.'
              break;
            case 12:
              that.tipTitle = 'Please note that'
              that.confirmInfo = 'After packing, the modified data is packed into the chain instead of the original transfer data, and the amount has actually arrived. However, due to the change of transaction ID, the modified transaction cannot be found, and the transaction result is displayed as "transaction not completed"'
              break;
          }
          return;
        }
        //52软分叉
        if(that.pageName == '52'){
          if(that.confirShow == true){
            switch(that.step){
              case 1:
                that.tipTiltle = 'Basic concepts and characteristics of soft bifurcation'
                that.confirmInfo = 'Bifurcation refers to the divergence of opinions when upgrading the blockchain, which leads to the bifurcation of the blockchain. According to the mutual compatibility of the new and old nodes after bifurcation, it can be divided into hard bifurcation and soft bifurcation. If the old node can not find the change of the new protocol and continue to accept the blocks dug up by the new node with the new protocol, this situation is called soft bifurcation.'
                break;
              default:
                that.tipTiltle = 'Please note that!'
                that.confirmInfo = 'Soft bifurcation simulation has ended, you can click Reset or return at the top right.'
                break;
             
            }
            return;
          }
        }
        //57硬分叉
        if(that.pageName == '57'){
          if(that.confirShow == true){
            switch(that.step){
              case 1:
                that.tipTiltle = 'The basic concept and characteristics of hard bifurcation'
                that.confirmInfo = 'Bifurcation refers to the divergence of opinions when upgrading the blockchain, which leads to the bifurcation of the blockchain. According to the mutual compatibility of the new and old nodes after bifurcation, it can be divided into hard bifurcation and soft bifurcation. When a new version of the software appears in the system and is not compatible with the previous version of the software, the old node cannot accept all or part of the blocks dug up by the new node, resulting in two chains at the same time, which is called hard bifurcation.'
                break;
              default:
                that.tipTiltle = 'Please note that!'
                that.confirmInfo = 'Hard bifurcation simulation has ended. You can click Reset or return at the top right.'
                break;
             
            }
            return;
          }
        }
        if(that.pageName == '53'){
          if(that.confirShow == true){
            switch(that.step){
              case 1:
                that.tipTiltle = 'Basic concepts and characteristics of replay attack'
                that.confirmInfo = 'Replay, as the name suggests, means replay. Replay attack, also known as replay attack and replay attack, means that the attacker sends a data packet received by the destination host to cheat the system. In blockchain technology, replay attacks usually occur when the blockchain is hard forked. Because the algorithms of address and private key production are the same, and the transaction format is the same, the transaction in one chain is likely to be completely legal in the other chain. If a transaction initiated on one chain is rebroadcast on another chain, it may also be confirmed. This is the replay attack of blockchain.'
                break;
              case 2:
                that.tipTiltle = 'Please note that!'
                that.confirmInfo = 'Transfer initiated successfully, please click broadcast button to broadcast.'
                break;
              case 3:
                that.tipTiltle = 'Please note that!'
                that.confirmInfo = 'Transfer initiated successfully, please click broadcast button to broadcast.'
                break;
              case 4:
                that.tipTiltle = 'Please note that!';
                that.confirmInfo = 'The hacker has successfully intercepted the transfer transaction from user a to user B!'
                break;
              case 5:
                that.tipTiltle = 'Please note that!';
                that.confirmInfo = 'The hacker has intercepted the transfer transaction from user a to user B and broadcast it in the B chain!'
                break;
              case 12:
                that.tipTiltle = 'Please note that!';
                that.confirmInfo = 'Because the B chain is generated after the hard bifurcation of the a chain, the verification method is consistent. Because of the characteristics of replay attack, the original transfer transaction and the transaction intercepted by the hacker to the B chain broadcast can be packaged and received, which also leads to the launch of a transfer transaction. Because of the replay attack, two sums of money are transferred out.'
                break;
            }
            return;
          }
        }
        if(that.pageName == '55'){
     
          if(that.confirShow == true){
            switch(that.step){
              case 1:
                that.tipTiltle = 'Basic concept and harmfulness of long range attack'
                that.confirmInfo = 'Long range attack means that the attacker creates a long blockchain branch starting from Genesis block and tries to replace the current legal main chain. The branch may have different transactions and blocks from the main chain, so this attack is also called replace history attack or history override attack. Malicious attackers can purchase a large number of token balance private keys, which have been used in the verification process. Next, malicious attackers can use the token balance to generate a blockchain replacement history, so as to give them more incentive based on proof of interest.'
                break;
              case 2:
                that.tipTiltle = 'Please note that!'
                that.confirmInfo = 'A chain has been out of some blocks, you can click the attack button in the left toolbox to start the next operation!'
                break;
              case 4:
                that.tipTiltle = 'Please note that!';
                that.confirmInfo = 'Because the block speed of B chain is higher than A chain, B chain covers A chain'
                break;
              case 5:
                that.tipTiltle = 'Please note that!';
                that.confirmInfo = 'So far, the simulation of long-range attack is over'
                break;
                
            }
            return;
          }
        }
        if(that.pageName == '56'){
          if(that.confirShow == true){
            switch(that.step){
              case 1:
                that.tipTiltle = 'The basic concept and harmfulness of contract loopholes'
                that.confirmInfo = 'The essence of smart contract is a piece of code running in the blockchain network, which completes the business logic given by users. But we know that as long as the program is written by people, there will be errors and defects. This scenario takes the common programming trap integer overflow vulnerability as an example. All integers in a computer have a width, so it has a maximum value that can be represented. Integer overflow occurs when saving a number that exceeds the maximum value. If we don not solve the problem of overflow, it will result in inaccurate data and wrong output of smart contract.'
                break;
              case 2:
                that.tipTiltle = 'Please note that!'
                that.confirmInfo = 'The balance is 0, the withdrawal contract is not verified, and the withdrawal of 1 yuan initiated by user a causes the balance to be'+ that.inputMoney +'yuan。'
                break;
             /* case 5:
                that.tipTiltle = 'Please note that!';
                that.confirmInfo = '合约漏洞攻击已结束，可点击右上方的重置或者返回。'
                break;*/
            }
            return;
          }
        }
			 
			}
		},
		methods:{
			sureTip(){
				this.$emit('tipSure')
			},
			//hash算法的时候，点击攻击与不攻击
			attackMode(num){
				this.$emit('attackMode',num)
				this.isAttack = num;
			},
			
			//椭圆线密码学显示划线
			showLine(){
				let that = this;
				that.a =that.a.replace(/[^1-3]/g,'')
				that.b =that.b.replace(/[^1-3]/g,'')
				if(that.a!='' && that.b!=''){
					 that.abimg=require('@/assets/ecc/'+that.a+''+that.b+'.jpg')
				}
			},
			//椭圆线已经生产点击确定
			sureLine(){
				let that = this;
				if(that.a ==''){
					that.$toast('Please enter a value for a',2000)
					return;
				}
				if(that.b == ''){
					that.$toast('Please enter the value of b',2000)
					return;
				}
				that.lineFinsh = true;
				that.$emit('sureLine')
			},
			//椭圆线计算新点点击确认
			surePoint(){
				let that = this;
				that.lineFinsh = false;
				that.$emit('surePoint');
			},
			//用户c解析完成确定
			sureParse(){
				this.$emit('sureParse');
			},
		
			// 提升算力点击确定
      sureUpCompute() {
        let that = this;
        if(that.upComputeUser == 'no one'){
      	  that.$toast('Please select promotion object',3000)
      	  return;
        }
        if(that.computevalue < 51) {
          that.$toast('Please increase the calculation power to at least 51%！')
          return;
        }
        that.$emit('sureUpCompute', that.upComputeUser)
      },
      
      // 转账
      sureTransfer(num) {
      	
        let that = this;
        if (that.tansferInfo.initiate == '') {
          that.$toast('Transfer initiator cannot be blank!',3000)
          return;
        }
        if (that.tansferInfo.object == '') {
          that.$toast('Transfer object cannot be empty!',3000)
          return;
        }
        if(that.tansferInfo.amount<0){
        	 that.$toast('Please input the amount must be a positive integer!',3000)
          return;
        }
         if (that.tansferInfo.amount == '' || that.tansferInfo.amount == 0) {
          that.$toast('Transfer amount cannot be greater than available balance!',3000)
          return;
        }
        if (that.tansferInfo.amount.match(/^-?[0-9]+$/) == null){
					that.$toast('Please input the amount must be a positive integer!')
					return
				}
       
        if(num==1){
        	 if (that.tansferInfo.amount > that.useBalance) {
		          that.$toast('Transfer amount cannot be greater than available balance!',3000)
		          return;
		        }
          }else{
        	 if (that.tansferInfo.amount > that.balance) {
		          that.$toast('Transfer amount cannot be greater than balance!',3000)
		          return;
		        }
        }
       
        that.$emit('sureTransfer',that.tansferInfo)
      },
      // 打包
      sureBale() {
        let that = this;
        that.$emit('sureBale')
      },
      del() {
        let that = this;
        that.$emit('del')
      },
      canc() {
        let that = this;
        that.$emit('canc')
      },
      // 确认修改金额
      sureEditAmount() {
        let that = this;
        if (this.selectIndexData==''){
          that.$toast('Please select the transaction to modify！',3000)
          return;
        }
        if (that.toEditAmount !== that.editAmount) {
          that.$toast('Please modify the amount as required!',3000)
          return;
        }
        that.$emit('sureEditAmount', that.selectIndexData)
      },
			//椭圆线计算新点点击确认
			surePoint(){
				let that = this;
				that.lineFinsh = false;
				that.$emit('surePoint');
			},
			//用户c解析完成确定
			sureParse(){
				this.$emit('sureParse');
			},
			surePrompt(){
				if(this.isRight){
					this.$emit('surePrompt',1);
				}else{
					this.$emit('surePrompt',0);	
				}
				
			},
			//重放攻击点击透明区域隐藏
			hideTrans(){
				this.$emit('hideTrans');
			},
			
			//重放攻击金额验证
			validateNum(value) { //验证只能填入数字
	    var reg = /(^([-]?)[1-9]([0-9]+)?(\.[0-9]{1,2})?$)|(^([-]?)(0){1}$)|(^([-]?)[0-9]\.[0-9]([0-9])?$)/
	     //验证警戒值
	    if(this.aa_vaule!='' && this.aa_vaule != undefined){
	    	if (!reg.test(this.aa_vaule)) {
	        this.$toast('Please enter a positive integer',2000)
	        this.aa_vaule='';
	        return ;
	    	}
	  	}
     },
			
      D1click(){
        let that = this;
        // console.log(that.inputMoney)
        // if(that.inputMoney == '' || that.inputMoney == undefined){
        //   that.$toast('请输入提现金额',2000)
        //   return;
        // }
        that.$emit('D1clickfinish');
      },
      //重放攻击确认转账
      D2click(){
        let that = this;  
        if(this.aa_vaule==''){
        	 this.$toast('Please enter the transfer amount',2000)
        	 return;
        }
        if(this.aa_vaule==0){
        	this.$toast('Please enter 3-digit positive integer balance',2000)
        	return;
        }
        if(this.aa_vaule<0){
        	this.$toast('The transfer amount must be a positive integer',2000)
        	return;
        }
        that.$emit('D2clickfinish',this.aa_vaule);
      },
      
      //点击转账对象下拉
      selectUser(val) {
			  let that = this;
			  that.toList=[];
			  for(var i = 0;i<that.userList.length;i++){
			  	if(val==that.userList[i].userId){
			  		that.balance = that.userList[i].balance
			  		that.useBalance = that.userList[i].useBalance
			  	}
			  	if(val!=that.userList[i].userId){
			  		that.toList.push(that.userList[i]);
			  	}
			  }
      },
      upToEditAmount(value) {
        let that = this;
        that.$emit('upToEditAmount',value);
        that.editAmount = '';
      },
      
      
      //51%转账点击透明隐藏
      hideLineDrawShow(){
      	this.$emit('hideLineDrawShow');
      },
      
			
		},
		mounted(){
			this.toList = this.userList
		}
		
		
		
	}
</script>

<style>
	.confirmBox51 .ivu-select{ vertical-align: top;}
	.confirmBox51 .ivu-input-wrapper{ vertical-align: top;}
</style>
<style scoped lang='less'>
	@import url("../assets/teachCss/tips.less");
  .a-mallattack-input{border:0 none; outline:none;font-size:14px;
  height: 30px;line-height: 30px; padding: 0 10px;}
</style>